# SHAP API Notebook

This is a template notebook. The first heading should be the title of what notebook is about. For example, if it is a neo4j tutorial the heading should be `Neo4j API`.

- Add description of what the notebook does.
- Point to references, e.g. (neo4j.API.md)
- Add citations.
- Keep the notebook flow clear.
- Comments should be imperative and have a period at the end.
- Your code should be well commented. 

The name of this notebook should in the following format:
- if the notebook is exploring `pycaret API`, then it is `pycaret.API.ipynb`

Follow the reference to write notebooks in a clear manner: https://github.com/causify-ai/helpers/blob/master/docs/coding/all.jupyter_notebook.how_to_guide.md

In [35]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Imports

In [51]:
import logging
import requests
import pandas as pd
import numpy as np
import sys
import os

# custom logic imports
from ingestion.fetch_data import load_config
from ingestion.dataset_builders import build_hourly_90d_dataset, build_daily_max_dataset

## Configuration

In [52]:
# hdbg.init_logger(verbosity=logging.INFO)

# _LOG = logging.getLogger(__name__)

# hprint.config_notebook()

In [53]:
# Add the src directory to the Python path
sys.path.append("../src")

In [54]:
config = load_config("config/config.yaml")

## Dataset Creation and Loading

In [58]:

df_hourly = build_hourly_90d_dataset(config)
df_daily = build_daily_max_dataset(config)

# Quick checks
print("Hourly:", df_hourly.shape)
print("Daily :", df_daily.shape)

[✓] Saved dataset to data/raw/hourly_90d/btc_hourly_90d_20250419_184326.csv
[✓] Saved dataset to data/raw/daily_max/btc_daily_max_20250419_184326.csv
Hourly: (2159, 4)
Daily : (366, 4)

In [56]:
df_hourly.head()

                timestamp          price    market_cap        volume
0 2025-01-19 22:03:47.721  103522.294062  2.053493e+12  6.071874e+10
1 2025-01-19 23:03:49.268  103221.869079  2.040376e+12  6.150783e+10
2 2025-01-20 00:00:35.807  101275.337148  2.014843e+12  7.297031e+10
3 2025-01-20 01:03:41.017   99717.609750  1.975730e+12  7.736650e+10
4 2025-01-20 02:03:33.559  100542.112601  1.982951e+12  9.075065e+10

In [57]:
df_daily.head()

   timestamp         price    market_cap        volume
0 2024-04-20  63988.818472  1.263308e+12  5.222779e+10
1 2024-04-21  64894.418691  1.277941e+12  1.660183e+10
2 2024-04-22  64936.420757  1.279764e+12  1.959212e+10
3 2024-04-23  66841.666852  1.317059e+12  2.774859e+10
4 2024-04-24  66406.952444  1.306843e+12  2.323223e+10